export interface EmojiEntry {
  emoji: string;
  label: string;
}

export const EMOJI_CATEGORIES = [
  "smileys",
  "people",
  "nature",
  "food",
  "activities",
  "travel",
  "objects",
  "symbols",
] as const;

export type EmojiCategory = (typeof EMOJI_CATEGORIES)[number];

export const EMOJI_BY_CATEGORY: Record<EmojiCategory, EmojiEntry[]> = {
  smileys: [
    { emoji: "😀", label: "grinning face" },
    { emoji: "😃", label: "grinning face with big eyes" },
    { emoji: "😄", label: "grinning face with smiling eyes" },
    { emoji: "😁", label: "beaming face with smiling eyes" },
    { emoji: "😆", label: "grinning squinting face" },
    { emoji: "😅", label: "grinning face with sweat" },
    { emoji: "🤣", label: "rolling on the floor laughing" },
    { emoji: "😂", label: "face with tears of joy" },
    { emoji: "🙂", label: "slightly smiling face" },
    { emoji: "🙃", label: "upside-down face" },
    { emoji: "😉", label: "winking face" },
    { emoji: "😊", label: "smiling face with smiling eyes" },
    { emoji: "😇", label: "smiling face with halo" },
    { emoji: "🥰", label: "smiling face with hearts" },
    { emoji: "😍", label: "smiling face with heart-eyes" },
    { emoji: "🤩", label: "star-struck" },
    { emoji: "😘", label: "face blowing a kiss" },
    { emoji: "😗", label: "kissing face" },
    { emoji: "😚", label: "kissing face with closed eyes" },
    { emoji: "😙", label: "kissing face with smiling eyes" },
    { emoji: "😋", label: "face savoring food" },
    { emoji: "😛", label: "face with tongue" },
    { emoji: "😜", label: "winking face with tongue" },
    { emoji: "🤪", label: "zany face" },
    { emoji: "😝", label: "squinting face with tongue" },
    { emoji: "🤑", label: "money-mouth face" },
    { emoji: "🤗", label: "smiling face with open hands" },
    { emoji: "🤭", label: "face with hand over mouth" },
    { emoji: "🤫", label: "shushing face" },
    { emoji: "🤔", label: "thinking face" },
    { emoji: "🤐", label: "zipper-mouth face" },
    { emoji: "🤨", label: "face with raised eyebrow" },
    { emoji: "😐", label: "neutral face" },
    { emoji: "😑", label: "expressionless face" },
    { emoji: "😶", label: "face without mouth" },
    { emoji: "😏", label: "smirking face" },
    { emoji: "😒", label: "unamused face" },
    { emoji: "🙄", label: "face with rolling eyes" },
    { emoji: "😬", label: "grimacing face" },
    { emoji: "🤥", label: "lying face" },
    { emoji: "😌", label: "relieved face" },
    { emoji: "😔", label: "pensive face" },
    { emoji: "😪", label: "sleepy face" },
    { emoji: "🤤", label: "drooling face" },
    { emoji: "😴", label: "sleeping face" },
    { emoji: "😷", label: "face with medical mask" },
    { emoji: "🤒", label: "face with thermometer" },
    { emoji: "🤕", label: "face with head-bandage" },
    { emoji: "🤢", label: "nauseated face" },
    { emoji: "🤮", label: "face vomiting" },
    { emoji: "🤧", label: "sneezing face" },
    { emoji: "🥵", label: "hot face" },
    { emoji: "🥶", label: "cold face" },
    { emoji: "🥴", label: "woozy face" },
    { emoji: "😵", label: "dizzy face" },
    { emoji: "🤯", label: "exploding head" },
    { emoji: "🤠", label: "cowboy hat face" },
    { emoji: "🥳", label: "partying face" },
    { emoji: "😎", label: "smiling face with sunglasses" },
    { emoji: "🤓", label: "nerd face" },
    { emoji: "🧐", label: "face with monocle" },
    { emoji: "😕", label: "confused face" },
    { emoji: "😟", label: "worried face" },
    { emoji: "🙁", label: "slightly frowning face" },
    { emoji: "☹️", label: "frowning face" },
    { emoji: "😮", label: "face with open mouth" },
    { emoji: "😯", label: "hushed face" },
    { emoji: "😲", label: "astonished face" },
    { emoji: "😳", label: "flushed face" },
    { emoji: "🥺", label: "pleading face" },
    { emoji: "😦", label: "frowning face with open mouth" },
    { emoji: "😧", label: "anguished face" },
    { emoji: "😨", label: "fearful face" },
    { emoji: "😰", label: "anxious face with sweat" },
    { emoji: "😥", label: "sad but relieved face" },
    { emoji: "😢", label: "crying face" },
    { emoji: "😭", label: "loudly crying face" },
    { emoji: "😱", label: "face screaming in fear" },
    { emoji: "😖", label: "confounded face" },
    { emoji: "😣", label: "persevering face" },
    { emoji: "😞", label: "disappointed face" },
    { emoji: "😓", label: "downcast face with sweat" },
    { emoji: "😩", label: "weary face" },
    { emoji: "😫", label: "tired face" },
    { emoji: "🥱", label: "yawning face" },
    { emoji: "😤", label: "face with steam from nose" },
    { emoji: "😡", label: "enraged face" },
    { emoji: "😠", label: "angry face" },
    { emoji: "🤬", label: "face with symbols on mouth" },
    { emoji: "😈", label: "smiling face with horns" },
    { emoji: "👿", label: "angry face with horns" },
    { emoji: "💀", label: "skull" },
    { emoji: "☠️", label: "skull and crossbones" },
    { emoji: "💩", label: "pile of poo" },
    { emoji: "🤡", label: "clown face" },
    { emoji: "👹", label: "ogre" },
    { emoji: "👺", label: "goblin" },
    { emoji: "👻", label: "ghost" },
    { emoji: "👽", label: "alien" },
    { emoji: "👾", label: "alien monster" },
    { emoji: "🤖", label: "robot" },
    { emoji: "😺", label: "grinning cat" },
    { emoji: "😸", label: "grinning cat with smiling eyes" },
    { emoji: "😹", label: "cat with tears of joy" },
    { emoji: "😻", label: "smiling cat with heart-eyes" },
    { emoji: "😼", label: "cat with wry smile" },
    { emoji: "😽", label: "kissing cat" },
    { emoji: "🙀", label: "weary cat" },
    { emoji: "😿", label: "crying cat" },
    { emoji: "😾", label: "pouting cat" },
  ],
  people: [
    { emoji: "👋", label: "waving hand" },
    { emoji: "🤚", label: "raised back of hand" },
    { emoji: "🖐️", label: "hand with fingers splayed" },
    { emoji: "✋", label: "raised hand" },
    { emoji: "🖖", label: "vulcan salute" },
    { emoji: "👌", label: "OK hand" },
    { emoji: "🤌", label: "pinched fingers" },
    { emoji: "🤏", label: "pinching hand" },
    { emoji: "✌️", label: "victory hand" },
    { emoji: "🤞", label: "crossed fingers" },
    { emoji: "🫰", label: "hand with index finger and thumb crossed" },
    { emoji: "🤟", label: "love-you gesture" },
    { emoji: "🤘", label: "sign of the horns" },
    { emoji: "🤙", label: "call me hand" },
    { emoji: "👈", label: "backhand index pointing left" },
    { emoji: "👉", label: "backhand index pointing right" },
    { emoji: "👆", label: "backhand index pointing up" },
    { emoji: "🖕", label: "middle finger" },
    { emoji: "👇", label: "backhand index pointing down" },
    { emoji: "☝️", label: "index pointing up" },
    { emoji: "👍", label: "thumbs up" },
    { emoji: "👎", label: "thumbs down" },
    { emoji: "✊", label: "raised fist" },
    { emoji: "👊", label: "oncoming fist" },
    { emoji: "🤛", label: "left-facing fist" },
    { emoji: "🤜", label: "right-facing fist" },
    { emoji: "👏", label: "clapping hands" },
    { emoji: "🙌", label: "raising hands" },
    { emoji: "🫶", label: "heart hands" },
    { emoji: "👐", label: "open hands" },
    { emoji: "🤲", label: "palms up together" },
    { emoji: "🤝", label: "handshake" },
    { emoji: "🙏", label: "folded hands" },
    { emoji: "✍️", label: "writing hand" },
    { emoji: "💅", label: "nail polish" },
    { emoji: "🤳", label: "selfie" },
    { emoji: "💪", label: "flexed biceps" },
    { emoji: "🦾", label: "mechanical arm" },
    { emoji: "🦿", label: "mechanical leg" },
    { emoji: "🦵", label: "leg" },
    { emoji: "🦶", label: "foot" },
    { emoji: "👂", label: "ear" },
    { emoji: "🦻", label: "ear with hearing aid" },
    { emoji: "👃", label: "nose" },
    { emoji: "🧠", label: "brain" },
    { emoji: "🫀", label: "anatomical heart" },
    { emoji: "🫁", label: "lungs" },
    { emoji: "🦷", label: "tooth" },
    { emoji: "🦴", label: "bone" },
    { emoji: "👀", label: "eyes" },
    { emoji: "👁️", label: "eye" },
    { emoji: "👅", label: "tongue" },
    { emoji: "👄", label: "mouth" },
    { emoji: "👶", label: "baby" },
    { emoji: "🧒", label: "child" },
    { emoji: "👦", label: "boy" },
    { emoji: "👧", label: "girl" },
    { emoji: "🧑", label: "person" },
    { emoji: "👱", label: "person blond hair" },
    { emoji: "👨", label: "man" },
    { emoji: "🧔", label: "person beard" },
    { emoji: "👩", label: "woman" },
    { emoji: "🧓", label: "older person" },
    { emoji: "👴", label: "old man" },
    { emoji: "👵", label: "old woman" },
  ],
  nature: [
    { emoji: "🐶", label: "dog face" },
    { emoji: "🐱", label: "cat face" },
    { emoji: "🐭", label: "mouse face" },
    { emoji: "🐹", label: "hamster" },
    { emoji: "🐰", label: "rabbit face" },
    { emoji: "🦊", label: "fox" },
    { emoji: "🐻", label: "bear" },
    { emoji: "🐼", label: "panda" },
    { emoji: "🐨", label: "koala" },
    { emoji: "🐯", label: "tiger face" },
    { emoji: "🦁", label: "lion" },
    { emoji: "🐮", label: "cow face" },
    { emoji: "🐷", label: "pig face" },
    { emoji: "🐽", label: "pig nose" },
    { emoji: "🐸", label: "frog" },
    { emoji: "🐵", label: "monkey face" },
    { emoji: "🐔", label: "chicken" },
    { emoji: "🐧", label: "penguin" },
    { emoji: "🐦", label: "bird" },
    { emoji: "🐤", label: "baby chick" },
    { emoji: "🦆", label: "duck" },
    { emoji: "🦅", label: "eagle" },
    { emoji: "🦉", label: "owl" },
    { emoji: "🦇", label: "bat" },
    { emoji: "🐺", label: "wolf" },
    { emoji: "🐗", label: "boar" },
    { emoji: "🐴", label: "horse face" },
    { emoji: "🦄", label: "unicorn" },
    { emoji: "🐝", label: "honeybee" },
    { emoji: "🐛", label: "bug" },
    { emoji: "🦋", label: "butterfly" },
    { emoji: "🐌", label: "snail" },
    { emoji: "🐞", label: "lady beetle" },
    { emoji: "🐜", label: "ant" },
    { emoji: "🦟", label: "mosquito" },
    { emoji: "🦗", label: "cricket" },
    { emoji: "🕷️", label: "spider" },
    { emoji: "🕸️", label: "spider web" },
    { emoji: "🐢", label: "turtle" },
    { emoji: "🐍", label: "snake" },
    { emoji: "🦎", label: "lizard" },
    { emoji: "🦖", label: "T-Rex" },
    { emoji: "🦕", label: "sauropod" },
    { emoji: "🐙", label: "octopus" },
    { emoji: "🦑", label: "squid" },
    { emoji: "🦐", label: "shrimp" },
    { emoji: "🦞", label: "lobster" },
    { emoji: "🦀", label: "crab" },
    { emoji: "🐡", label: "blowfish" },
    { emoji: "🐠", label: "tropical fish" },
    { emoji: "🐟", label: "fish" },
    { emoji: "🐬", label: "dolphin" },
    { emoji: "🐳", label: "spouting whale" },
    { emoji: "🐋", label: "whale" },
    { emoji: "🦈", label: "shark" },
    { emoji: "🐊", label: "crocodile" },
    { emoji: "🐅", label: "tiger" },
    { emoji: "🐆", label: "leopard" },
    { emoji: "🦓", label: "zebra" },
    { emoji: "🦍", label: "gorilla" },
    { emoji: "🦧", label: "orangutan" },
    { emoji: "🐘", label: "elephant" },
    { emoji: "🦛", label: "hippopotamus" },
    { emoji: "🦏", label: "rhinoceros" },
    { emoji: "🐪", label: "camel" },
    { emoji: "🐫", label: "two-hump camel" },
    { emoji: "🦒", label: "giraffe" },
    { emoji: "🦘", label: "kangaroo" },
    { emoji: "🐃", label: "water buffalo" },
    { emoji: "🐂", label: "ox" },
    { emoji: "🐄", label: "cow" },
    { emoji: "🐎", label: "horse" },
    { emoji: "🐖", label: "pig" },
    { emoji: "🐏", label: "ram" },
    { emoji: "🐑", label: "ewe" },
    { emoji: "🦙", label: "llama" },
    { emoji: "🐐", label: "goat" },
    { emoji: "🦌", label: "deer" },
    { emoji: "🐕", label: "dog" },
    { emoji: "🐩", label: "poodle" },
    { emoji: "🦮", label: "guide dog" },
    { emoji: "🐕‍🦺", label: "service dog" },
    { emoji: "🐈", label: "cat" },
    { emoji: "🐈‍⬛", label: "black cat" },
    { emoji: "🐓", label: "rooster" },
    { emoji: "🦃", label: "turkey" },
    { emoji: "🦚", label: "peacock" },
    { emoji: "🦜", label: "parrot" },
    { emoji: "🦢", label: "swan" },
    { emoji: "🦩", label: "flamingo" },
    { emoji: "🕊️", label: "dove" },
    { emoji: "🐇", label: "rabbit" },
    { emoji: "🦝", label: "raccoon" },
    { emoji: "🦨", label: "skunk" },
    { emoji: "🦡", label: "badger" },
    { emoji: "🦫", label: "beaver" },
    { emoji: "🦦", label: "otter" },
    { emoji: "🦥", label: "sloth" },
    { emoji: "🐁", label: "mouse" },
    { emoji: "🐀", label: "rat" },
    { emoji: "🐿️", label: "chipmunk" },
    { emoji: "🦔", label: "hedgehog" },
    { emoji: "🌵", label: "cactus" },
    { emoji: "🎄", label: "Christmas tree" },
    { emoji: "🌲", label: "evergreen tree" },
    { emoji: "🌳", label: "deciduous tree" },
    { emoji: "🌴", label: "palm tree" },
    { emoji: "🌱", label: "seedling" },
    { emoji: "🌿", label: "herb" },
    { emoji: "☘️", label: "shamrock" },
    { emoji: "🍀", label: "four leaf clover" },
    { emoji: "🎍", label: "pine decoration" },
    { emoji: "🪴", label: "potted plant" },
    { emoji: "🎋", label: "tanabata tree" },
    { emoji: "🍃", label: "leaf fluttering in wind" },
    { emoji: "🍂", label: "fallen leaf" },
    { emoji: "🍁", label: "maple leaf" },
    { emoji: "🍄", label: "mushroom" },
    { emoji: "🌾", label: "sheaf of rice" },
    { emoji: "💐", label: "bouquet" },
    { emoji: "🌷", label: "tulip" },
    { emoji: "🌹", label: "rose" },
    { emoji: "🥀", label: "wilted flower" },
    { emoji: "🌺", label: "hibiscus" },
    { emoji: "🌸", label: "cherry blossom" },
    { emoji: "🌼", label: "blossom" },
    { emoji: "🌻", label: "sunflower" },
    { emoji: "🌞", label: "sun with face" },
    { emoji: "🌝", label: "full moon face" },
    { emoji: "🌛", label: "first quarter moon face" },
    { emoji: "🌜", label: "last quarter moon face" },
    { emoji: "🌚", label: "new moon face" },
    { emoji: "🌕", label: "full moon" },
    { emoji: "🌖", label: "waning gibbous moon" },
    { emoji: "🌗", label: "last quarter moon" },
    { emoji: "🌘", label: "waning crescent moon" },
    { emoji: "🌑", label: "new moon" },
    { emoji: "🌒", label: "waxing crescent moon" },
    { emoji: "🌓", label: "first quarter moon" },
    { emoji: "🌔", label: "waxing gibbous moon" },
    { emoji: "🌙", label: "crescent moon" },
    { emoji: "🌎", label: "globe showing Americas" },
    { emoji: "🌍", label: "globe showing Europe-Africa" },
    { emoji: "🌏", label: "globe showing Asia-Australia" },
    { emoji: "🪐", label: "ringed planet" },
    { emoji: "💫", label: "dizzy" },
    { emoji: "⭐", label: "star" },
    { emoji: "🌟", label: "glowing star" },
    { emoji: "✨", label: "sparkles" },
    { emoji: "⚡", label: "high voltage" },
    { emoji: "🔥", label: "fire" },
    { emoji: "💥", label: "collision" },
    { emoji: "☄️", label: "comet" },
    { emoji: "☀️", label: "sun" },
    { emoji: "🌤️", label: "sun behind small cloud" },
    { emoji: "⛅", label: "sun behind cloud" },
    { emoji: "🌥️", label: "sun behind large cloud" },
    { emoji: "🌦️", label: "sun behind rain cloud" },
    { emoji: "🌈", label: "rainbow" },
    { emoji: "☁️", label: "cloud" },
    { emoji: "🌧️", label: "cloud with rain" },
    { emoji: "⛈️", label: "cloud with lightning and rain" },
    { emoji: "🌩️", label: "cloud with lightning" },
    { emoji: "🌨️", label: "cloud with snow" },
    { emoji: "❄️", label: "snowflake" },
    { emoji: "☃️", label: "snowman" },
    { emoji: "⛄", label: "snowman without snow" },
    { emoji: "🌬️", label: "wind face" },
    { emoji: "💨", label: "dashing away" },
    { emoji: "🌊", label: "water wave" },
    { emoji: "💧", label: "droplet" },
    { emoji: "💦", label: "sweat droplets" },
    { emoji: "☔", label: "umbrella with rain drops" },
  ],
  food: [
    { emoji: "🍏", label: "green apple" },
    { emoji: "🍎", label: "red apple" },
    { emoji: "🍐", label: "pear" },
    { emoji: "🍊", label: "tangerine" },
    { emoji: "🍋", label: "lemon" },
    { emoji: "🍌", label: "banana" },
    { emoji: "🍉", label: "watermelon" },
    { emoji: "🍇", label: "grapes" },
    { emoji: "🍓", label: "strawberry" },
    { emoji: "🫐", label: "blueberries" },
    { emoji: "🍈", label: "melon" },
    { emoji: "🍒", label: "cherries" },
    { emoji: "🍑", label: "peach" },
    { emoji: "🍍", label: "pineapple" },
    { emoji: "🥝", label: "kiwi fruit" },
    { emoji: "🍅", label: "tomato" },
    { emoji: "🥑", label: "avocado" },
    { emoji: "🍆", label: "eggplant" },
    { emoji: "🥔", label: "potato" },
    { emoji: "🥕", label: "carrot" },
    { emoji: "🌽", label: "ear of corn" },
    { emoji: "🌶️", label: "hot pepper" },
    { emoji: "🫑", label: "bell pepper" },
    { emoji: "🥒", label: "cucumber" },
    { emoji: "🥬", label: "leafy green" },
    { emoji: "🥦", label: "broccoli" },
    { emoji: "🧄", label: "garlic" },
    { emoji: "🧅", label: "onion" },
    { emoji: "🍄", label: "mushroom" },
    { emoji: "🥜", label: "peanuts" },
    { emoji: "🌰", label: "chestnut" },
    { emoji: "🍞", label: "bread" },
    { emoji: "🥐", label: "croissant" },
    { emoji: "🥖", label: "baguette bread" },
    { emoji: "🥨", label: "pretzel" },
    { emoji: "🥯", label: "bagel" },
    { emoji: "🥞", label: "pancakes" },
    { emoji: "🧇", label: "waffle" },
    { emoji: "🧀", label: "cheese wedge" },
    { emoji: "🍖", label: "meat on bone" },
    { emoji: "🍗", label: "poultry leg" },
    { emoji: "🥩", label: "cut of meat" },
    { emoji: "🥓", label: "bacon" },
    { emoji: "🍔", label: "hamburger" },
    { emoji: "🍟", label: "french fries" },
    { emoji: "🍕", label: "pizza" },
    { emoji: "🌭", label: "hot dog" },
    { emoji: "🥪", label: "sandwich" },
    { emoji: "🌮", label: "taco" },
    { emoji: "🌯", label: "burrito" },
    { emoji: "🫔", label: "tamale" },
    { emoji: "🥙", label: "stuffed flatbread" },
    { emoji: "🧆", label: "falafel" },
    { emoji: "🥚", label: "egg" },
    { emoji: "🍳", label: "cooking" },
    { emoji: "🥘", label: "shallow pan of food" },
    { emoji: "🍲", label: "pot of food" },
    { emoji: "🫕", label: "fondue" },
    { emoji: "🥣", label: "bowl with spoon" },
    { emoji: "🥗", label: "green salad" },
    { emoji: "🍿", label: "popcorn" },
    { emoji: "🧈", label: "butter" },
    { emoji: "🧂", label: "salt" },
    { emoji: "🥫", label: "canned food" },
    { emoji: "🍱", label: "bento box" },
    { emoji: "🍘", label: "rice cracker" },
    { emoji: "🍙", label: "rice ball" },
    { emoji: "🍚", label: "cooked rice" },
    { emoji: "🍛", label: "curry rice" },
    { emoji: "🍜", label: "steaming bowl" },
    { emoji: "🍝", label: "spaghetti" },
    { emoji: "🍠", label: "roasted sweet potato" },
    { emoji: "🍢", label: "oden" },
    { emoji: "🍣", label: "sushi" },
    { emoji: "🍤", label: "fried shrimp" },
    { emoji: "🍥", label: "fish cake with swirl" },
    { emoji: "🥮", label: "moon cake" },
    { emoji: "🍡", label: "dango" },
    { emoji: "🥟", label: "dumpling" },
    { emoji: "🥠", label: "fortune cookie" },
    { emoji: "🥡", label: "takeout box" },
    { emoji: "🦪", label: "oyster" },
    { emoji: "🍦", label: "soft ice cream" },
    { emoji: "🍧", label: "shaved ice" },
    { emoji: "🍨", label: "ice cream" },
    { emoji: "🍩", label: "doughnut" },
    { emoji: "🍪", label: "cookie" },
    { emoji: "🎂", label: "birthday cake" },
    { emoji: "🍰", label: "shortcake" },
    { emoji: "🧁", label: "cupcake" },
    { emoji: "🥧", label: "pie" },
    { emoji: "🍫", label: "chocolate bar" },
    { emoji: "🍬", label: "candy" },
    { emoji: "🍭", label: "lollipop" },
    { emoji: "🍮", label: "custard" },
    { emoji: "🍯", label: "honey pot" },
    { emoji: "🍼", label: "baby bottle" },
    { emoji: "🥛", label: "glass of milk" },
    { emoji: "☕", label: "hot beverage" },
    { emoji: "🫖", label: "teapot" },
    { emoji: "🍵", label: "teacup without handle" },
    { emoji: "🍶", label: "sake" },
    { emoji: "🍾", label: "bottle with popping cork" },
    { emoji: "🍷", label: "wine glass" },
    { emoji: "🍸", label: "cocktail glass" },
    { emoji: "🍹", label: "tropical drink" },
    { emoji: "🍺", label: "beer mug" },
    { emoji: "🍻", label: "clinking beer mugs" },
    { emoji: "🥂", label: "clinking glasses" },
    { emoji: "🥃", label: "tumbler glass" },
    { emoji: "🫗", label: "pouring liquid" },
    { emoji: "🥤", label: "cup with straw" },
    { emoji: "🧋", label: "bubble tea" },
    { emoji: "🧃", label: "beverage box" },
    { emoji: "🧉", label: "mate" },
    { emoji: "🥢", label: "chopsticks" },
    { emoji: "🍽️", label: "fork and knife with plate" },
    { emoji: "🍴", label: "fork and knife" },
    { emoji: "🥄", label: "spoon" },
  ],
  activities: [
    { emoji: "⚽", label: "soccer ball" },
    { emoji: "🏀", label: "basketball" },
    { emoji: "🏈", label: "american football" },
    { emoji: "⚾", label: "baseball" },
    { emoji: "🥎", label: "softball" },
    { emoji: "🎾", label: "tennis" },
    { emoji: "🏐", label: "volleyball" },
    { emoji: "🏉", label: "rugby football" },
    { emoji: "🥏", label: "flying disc" },
    { emoji: "🎱", label: "pool 8 ball" },
    { emoji: "🪀", label: "yo-yo" },
    { emoji: "🏓", label: "ping pong" },
    { emoji: "🏸", label: "badminton" },
    { emoji: "🏒", label: "ice hockey" },
    { emoji: "🏑", label: "field hockey" },
    { emoji: "🥍", label: "lacrosse" },
    { emoji: "🏏", label: "cricket game" },
    { emoji: "🥅", label: "goal net" },
    { emoji: "⛳", label: "flag in hole" },
    { emoji: "🪁", label: "kite" },
    { emoji: "🏹", label: "bow and arrow" },
    { emoji: "🎣", label: "fishing pole" },
    { emoji: "🤿", label: "diving mask" },
    { emoji: "🥊", label: "boxing glove" },
    { emoji: "🥋", label: "martial arts uniform" },
    { emoji: "🎽", label: "running shirt" },
    { emoji: "🛹", label: "skateboard" },
    { emoji: "🛼", label: "roller skate" },
    { emoji: "🛷", label: "sled" },
    { emoji: "⛸️", label: "ice skate" },
    { emoji: "🥌", label: "curling stone" },
    { emoji: "🎿", label: "skis" },
    { emoji: "⛷️", label: "skier" },
    { emoji: "🏂", label: "snowboarder" },
    { emoji: "🏋️", label: "person lifting weights" },
    { emoji: "🤼", label: "people wrestling" },
    { emoji: "🤸", label: "person cartwheeling" },
    { emoji: "⛹️", label: "person bouncing ball" },
    { emoji: "🤺", label: "person fencing" },
    { emoji: "🤾", label: "person playing handball" },
    { emoji: "🏌️", label: "person golfing" },
    { emoji: "🏇", label: "horse racing" },
    { emoji: "🧘", label: "person in lotus position" },
    { emoji: "🏄", label: "person surfing" },
    { emoji: "🏊", label: "person swimming" },
    { emoji: "🤽", label: "person playing water polo" },
    { emoji: "🚣", label: "person rowing boat" },
    { emoji: "🧗", label: "person climbing" },
    { emoji: "🚵", label: "person mountain biking" },
    { emoji: "🚴", label: "person biking" },
    { emoji: "🏆", label: "trophy" },
    { emoji: "🥇", label: "1st place medal" },
    { emoji: "🥈", label: "2nd place medal" },
    { emoji: "🥉", label: "3rd place medal" },
    { emoji: "🏅", label: "sports medal" },
    { emoji: "🎖️", label: "military medal" },
    { emoji: "🏵️", label: "rosette" },
    { emoji: "🎗️", label: "reminder ribbon" },
    { emoji: "🎫", label: "ticket" },
    { emoji: "🎟️", label: "admission tickets" },
    { emoji: "🎪", label: "circus tent" },
    { emoji: "🤹", label: "person juggling" },
    { emoji: "🎭", label: "performing arts" },
    { emoji: "🩰", label: "ballet shoes" },
    { emoji: "🎨", label: "artist palette" },
    { emoji: "🎬", label: "clapper board" },
    { emoji: "🎤", label: "microphone" },
    { emoji: "🎧", label: "headphone" },
    { emoji: "🎼", label: "musical score" },
    { emoji: "🎹", label: "musical keyboard" },
    { emoji: "🥁", label: "drum" },
    { emoji: "🎷", label: "saxophone" },
    { emoji: "🎺", label: "trumpet" },
    { emoji: "🎸", label: "guitar" },
    { emoji: "🪕", label: "banjo" },
    { emoji: "🎻", label: "violin" },
    { emoji: "🎲", label: "game die" },
    { emoji: "♟️", label: "chess pawn" },
    { emoji: "🎯", label: "bullseye" },
    { emoji: "🎳", label: "bowling" },
    { emoji: "🎮", label: "video game" },
    { emoji: "🎰", label: "slot machine" },
    { emoji: "🧩", label: "puzzle piece" },
  ],
  travel: [
    { emoji: "🚗", label: "automobile" },
    { emoji: "🚕", label: "taxi" },
    { emoji: "🚙", label: "sport utility vehicle" },
    { emoji: "🚌", label: "bus" },
    { emoji: "🚎", label: "trolleybus" },
    { emoji: "🏎️", label: "racing car" },
    { emoji: "🚓", label: "police car" },
    { emoji: "🚑", label: "ambulance" },
    { emoji: "🚒", label: "fire engine" },
    { emoji: "🚐", label: "minibus" },
    { emoji: "🚚", label: "delivery truck" },
    { emoji: "🚛", label: "articulated lorry" },
    { emoji: "🚜", label: "tractor" },
    { emoji: "🦯", label: "white cane" },
    { emoji: "🦽", label: "manual wheelchair" },
    { emoji: "🦼", label: "motorized wheelchair" },
    { emoji: "🛴", label: "kick scooter" },
    { emoji: "🚲", label: "bicycle" },
    { emoji: "🛵", label: "motor scooter" },
    { emoji: "🏍️", label: "motorcycle" },
    { emoji: "🛺", label: "auto rickshaw" },
    { emoji: "🚨", label: "police car light" },
    { emoji: "🚥", label: "horizontal traffic light" },
    { emoji: "🚦", label: "vertical traffic light" },
    { emoji: "🛑", label: "stop sign" },
    { emoji: "🚧", label: "construction" },
    { emoji: "⚓", label: "anchor" },
    { emoji: "⛵", label: "sailboat" },
    { emoji: "🛶", label: "canoe" },
    { emoji: "🚤", label: "speedboat" },
    { emoji: "🛳️", label: "passenger ship" },
    { emoji: "⛴️", label: "ferry" },
    { emoji: "🛥️", label: "motor boat" },
    { emoji: "🚢", label: "ship" },
    { emoji: "✈️", label: "airplane" },
    { emoji: "🛩️", label: "small airplane" },
    { emoji: "🛫", label: "airplane departure" },
    { emoji: "🛬", label: "airplane arrival" },
    { emoji: "🪂", label: "parachute" },
    { emoji: "💺", label: "seat" },
    { emoji: "🚁", label: "helicopter" },
    { emoji: "🚟", label: "suspension railway" },
    { emoji: "🚠", label: "mountain cableway" },
    { emoji: "🚡", label: "aerial tramway" },
    { emoji: "🛰️", label: "satellite" },
    { emoji: "🚀", label: "rocket" },
    { emoji: "🛸", label: "flying saucer" },
    { emoji: "🌠", label: "shooting star" },
    { emoji: "🌌", label: "milky way" },
    { emoji: "⛺", label: "tent" },
    { emoji: "🌁", label: "foggy" },
    { emoji: "🌃", label: "night with stars" },
    { emoji: "🏙️", label: "cityscape" },
    { emoji: "🌄", label: "sunrise over mountains" },
    { emoji: "🌅", label: "sunrise" },
    { emoji: "🌆", label: "cityscape at dusk" },
    { emoji: "🌇", label: "sunset" },
    { emoji: "🌉", label: "bridge at night" },
    { emoji: "♨️", label: "hot springs" },
    { emoji: "🎠", label: "carousel horse" },
    { emoji: "🎡", label: "ferris wheel" },
    { emoji: "🎢", label: "roller coaster" },
    { emoji: "💈", label: "barber pole" },
    { emoji: "🎪", label: "circus tent" },
  ],
  objects: [
    { emoji: "⌚", label: "watch" },
    { emoji: "📱", label: "mobile phone" },
    { emoji: "📲", label: "mobile phone with arrow" },
    { emoji: "💻", label: "laptop" },
    { emoji: "⌨️", label: "keyboard" },
    { emoji: "🖥️", label: "desktop computer" },
    { emoji: "🖨️", label: "printer" },
    { emoji: "🖱️", label: "computer mouse" },
    { emoji: "🖲️", label: "trackball" },
    { emoji: "🕹️", label: "joystick" },
    { emoji: "🗜️", label: "clamp" },
    { emoji: "💽", label: "computer disk" },
    { emoji: "💾", label: "floppy disk" },
    { emoji: "💿", label: "optical disk" },
    { emoji: "📀", label: "dvd" },
    { emoji: "📼", label: "videocassette" },
    { emoji: "📷", label: "camera" },
    { emoji: "📸", label: "camera with flash" },
    { emoji: "📹", label: "video camera" },
    { emoji: "🎥", label: "movie camera" },
    { emoji: "📽️", label: "film projector" },
    { emoji: "🎞️", label: "film frames" },
    { emoji: "📞", label: "telephone receiver" },
    { emoji: "☎️", label: "telephone" },
    { emoji: "📟", label: "pager" },
    { emoji: "📠", label: "fax machine" },
    { emoji: "📺", label: "television" },
    { emoji: "📻", label: "radio" },
    { emoji: "🎙️", label: "studio microphone" },
    { emoji: "🎚️", label: "level slider" },
    { emoji: "🎛️", label: "control knobs" },
    { emoji: "🧭", label: "compass" },
    { emoji: "⏱️", label: "stopwatch" },
    { emoji: "⏲️", label: "timer clock" },
    { emoji: "⏰", label: "alarm clock" },
    { emoji: "🕰️", label: "mantelpiece clock" },
    { emoji: "⌛", label: "hourglass done" },
    { emoji: "⏳", label: "hourglass not done" },
    { emoji: "📡", label: "satellite antenna" },
    { emoji: "🔋", label: "battery" },
    { emoji: "🪫", label: "low battery" },
    { emoji: "🔌", label: "electric plug" },
    { emoji: "💡", label: "light bulb" },
    { emoji: "🔦", label: "flashlight" },
    { emoji: "🕯️", label: "candle" },
    { emoji: "🪔", label: "diya lamp" },
    { emoji: "🧯", label: "fire extinguisher" },
    { emoji: "🛢️", label: "oil drum" },
    { emoji: "💸", label: "money with wings" },
    { emoji: "💵", label: "dollar banknote" },
    { emoji: "💴", label: "yen banknote" },
    { emoji: "💶", label: "euro banknote" },
    { emoji: "💷", label: "pound banknote" },
    { emoji: "🪙", label: "coin" },
    { emoji: "💰", label: "money bag" },
    { emoji: "💳", label: "credit card" },
    { emoji: "🧾", label: "receipt" },
    { emoji: "💎", label: "gem stone" },
    { emoji: "⚖️", label: "balance scale" },
    { emoji: "🦯", label: "white cane" },
    { emoji: "🧰", label: "toolbox" },
    { emoji: "🧲", label: "magnet" },
    { emoji: "🧪", label: "test tube" },
    { emoji: "🧫", label: "petri dish" },
    { emoji: "🧬", label: "dna" },
    { emoji: "🔬", label: "microscope" },
    { emoji: "🔭", label: "telescope" },
    { emoji: "💉", label: "syringe" },
    { emoji: "🩸", label: "drop of blood" },
    { emoji: "💊", label: "pill" },
    { emoji: "🩹", label: "adhesive bandage" },
    { emoji: "🩼", label: "crutch" },
    { emoji: "🩺", label: "stethoscope" },
    { emoji: "🌡️", label: "thermometer" },
    { emoji: "🧹", label: "broom" },
    { emoji: "🧺", label: "basket" },
    { emoji: "🧻", label: "roll of paper" },
    { emoji: "🚽", label: "toilet" },
    { emoji: "🪠", label: "plunger" },
    { emoji: "🚿", label: "shower" },
    { emoji: "🛁", label: "bathtub" },
    { emoji: "🪤", label: "mouse trap" },
    { emoji: "🪒", label: "razor" },
    { emoji: "🧴", label: "lotion bottle" },
    { emoji: "🧷", label: "safety pin" },
    { emoji: "🪣", label: "bucket" },
    { emoji: "🧼", label: "soap" },
    { emoji: "🫧", label: "bubbles" },
    { emoji: "🪥", label: "toothbrush" },
    { emoji: "🧽", label: "sponge" },
    { emoji: "🛒", label: "shopping cart" },
    { emoji: "🚬", label: "cigarette" },
    { emoji: "⚰️", label: "coffin" },
    { emoji: "🪦", label: "headstone" },
    { emoji: "⚱️", label: "funeral urn" },
    { emoji: "🗿", label: "moai" },
    { emoji: "🪧", label: "placard" },
    { emoji: "🪪", label: "identification card" },
    { emoji: "🏧", label: "ATM sign" },
    { emoji: "🚮", label: "litter in bin sign" },
    { emoji: "🚰", label: "potable water" },
    { emoji: "♿", label: "wheelchair symbol" },
    { emoji: "🚹", label: "men’s room" },
    { emoji: "🚺", label: "women’s room" },
    { emoji: "🚻", label: "restroom" },
    { emoji: "🚼", label: "baby symbol" },
    { emoji: "🚾", label: "water closet" },
    { emoji: "🛂", label: "passport control" },
    { emoji: "🛃", label: "customs" },
    { emoji: "🛄", label: "baggage claim" },
    { emoji: "🛅", label: "left luggage" },
  ],
  symbols: [
    { emoji: "❤️", label: "red heart" },
    { emoji: "🧡", label: "orange heart" },
    { emoji: "💛", label: "yellow heart" },
    { emoji: "💚", label: "green heart" },
    { emoji: "💙", label: "blue heart" },
    { emoji: "💜", label: "purple heart" },
    { emoji: "🖤", label: "black heart" },
    { emoji: "🤍", label: "white heart" },
    { emoji: "🤎", label: "brown heart" },
    { emoji: "💔", label: "broken heart" },
    { emoji: "❣️", label: "heart exclamation" },
    { emoji: "💕", label: "two hearts" },
    { emoji: "💞", label: "revolving hearts" },
    { emoji: "💓", label: "beating heart" },
    { emoji: "💗", label: "growing heart" },
    { emoji: "💖", label: "sparkling heart" },
    { emoji: "💘", label: "heart with arrow" },
    { emoji: "💝", label: "heart with ribbon" },
    { emoji: "💟", label: "heart decoration" },
    { emoji: "☮️", label: "peace symbol" },
    { emoji: "✝️", label: "latin cross" },
    { emoji: "☪️", label: "star and crescent" },
    { emoji: "🕉️", label: "om" },
    { emoji: "☸️", label: "wheel of dharma" },
    { emoji: "✡️", label: "star of David" },
    { emoji: "🔯", label: "dotted six-pointed star" },
    { emoji: "🕎", label: "menorah" },
    { emoji: "☯️", label: "yin yang" },
    { emoji: "☦️", label: "orthodox cross" },
    { emoji: "🛐", label: "place of worship" },
    { emoji: "⛎", label: "Ophiuchus" },
    { emoji: "♈", label: "Aries" },
    { emoji: "♉", label: "Taurus" },
    { emoji: "♊", label: "Gemini" },
    { emoji: "♋", label: "Cancer" },
    { emoji: "♌", label: "Leo" },
    { emoji: "♍", label: "Virgo" },
    { emoji: "♎", label: "Libra" },
    { emoji: "♏", label: "Scorpio" },
    { emoji: "♐", label: "Sagittarius" },
    { emoji: "♑", label: "Capricorn" },
    { emoji: "♒", label: "Aquarius" },
    { emoji: "♓", label: "Pisces" },
    { emoji: "🆔", label: "ID button" },
    { emoji: "⚛️", label: "atom symbol" },
    { emoji: "🉑", label: "Japanese acceptable button" },
    { emoji: "☢️", label: "radioactive" },
    { emoji: "☣️", label: "biohazard" },
    { emoji: "📴", label: "mobile phone off" },
    { emoji: "📳", label: "vibration mode" },
    { emoji: "🈶", label: "Japanese not free of charge button" },
    { emoji: "🈚", label: "Japanese free of charge button" },
    { emoji: "🈸", label: "Japanese application button" },
    { emoji: "🈺", label: "Japanese open for business button" },
    { emoji: "🈷️", label: "Japanese monthly amount button" },
    { emoji: "✴️", label: "eight-pointed star" },
    { emoji: "🆚", label: "VS button" },
    { emoji: "💮", label: "white flower" },
    { emoji: "🉐", label: "Japanese bargain button" },
    { emoji: "㊙️", label: "Japanese secret button" },
    { emoji: "㊗️", label: "Japanese congratulations button" },
    { emoji: "🈴", label: "Japanese passing grade button" },
    { emoji: "🈵", label: "Japanese no vacancy button" },
    { emoji: "🈹", label: "Japanese discount button" },
    { emoji: "🈲", label: "Japanese prohibited button" },
    { emoji: "🅰️", label: "A button" },
    { emoji: "🅱️", label: "B button" },
    { emoji: "🆎", label: "AB button" },
    { emoji: "🅾️", label: "O button" },
    { emoji: "💠", label: "diamond with a dot" },
    { emoji: "♻️", label: "recycling symbol" },
    { emoji: "🔱", label: "trident emblem" },
    { emoji: "📛", label: "name badge" },
    { emoji: "🔰", label: "Japanese symbol for beginner" },
    { emoji: "⭕", label: "heavy large circle" },
    { emoji: "✅", label: "check mark button" },
    { emoji: "☑️", label: "check box with check" },
    { emoji: "✔️", label: "check mark" },
    { emoji: "❌", label: "cross mark" },
    { emoji: "❎", label: "cross mark button" },
    { emoji: "➰", label: "curly loop" },
    { emoji: "➿", label: "double curly loop" },
    { emoji: "〽️", label: "part alternation mark" },
    { emoji: "✳️", label: "eight-spoked asterisk" },
    { emoji: "❇️", label: "sparkle" },
    { emoji: "©️", label: "copyright" },
    { emoji: "®️", label: "registered" },
    { emoji: "™️", label: "trade mark" },
    { emoji: "💯", label: "hundred points" },
    { emoji: "🔚", label: "END arrow" },
    { emoji: "🔙", label: "BACK arrow" },
    { emoji: "🔛", label: "ON arrow" },
    { emoji: "🔝", label: "TOP arrow" },
    { emoji: "🔜", label: "SOON arrow" },
    { emoji: "🌀", label: "cyclone" },
    { emoji: "♠️", label: "spade suit" },
    { emoji: "♥️", label: "heart suit" },
    { emoji: "♦️", label: "diamond suit" },
    { emoji: "♣️", label: "club suit" },
    { emoji: "🃏", label: "joker" },
    { emoji: "🀄", label: "mahjong red dragon" },
    { emoji: "🎴", label: "flower playing cards" },
    { emoji: "🔇", label: "muted speaker" },
    { emoji: "🔈", label: "speaker low volume" },
    { emoji: "🔉", label: "speaker medium volume" },
    { emoji: "🔊", label: "speaker high volume" },
    { emoji: "🔔", label: "bell" },
    { emoji: "🔕", label: "bell with slash" },
    { emoji: "🎵", label: "musical note" },
    { emoji: "🎶", label: "musical notes" },
    { emoji: "🎙️", label: "studio microphone" },
    { emoji: "🎚️", label: "level slider" },
    { emoji: "🎛️", label: "control knobs" },
    { emoji: "🎤", label: "microphone" },
    { emoji: "🎧", label: "headphone" },
    { emoji: "📻", label: "radio" },
    { emoji: "🎷", label: "saxophone" },
    { emoji: "🪗", label: "accordion" },
    { emoji: "🎸", label: "guitar" },
    { emoji: "🎹", label: "musical keyboard" },
    { emoji: "🎺", label: "trumpet" },
    { emoji: "🎻", label: "violin" },
    { emoji: "🥁", label: "drum" },
  ],
};
